name: SCANOSS Int Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  scanoss-code-scan:
    name: SCANOSS Code Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SCANOSS Code Scan
        id: scanoss-code-scan-step
        uses: scanoss/code-scan-action@feat/SP-3125_delta-scan
        with:
          policies: cpl, und
          api.key: ${{ secrets.SC_API_KEY }}
          runtimeContainer: 'ghcr.io/scanoss/scanoss-py:feat/SP-3354_delta-scan-setup'
          scanMode: 'delta'

