name: Scanoss - comp1

on:
  push:
    paths:
      - 'comp1/**'
  pull_request:
    paths:
      - 'comp1/**'


jobs:
  call-scanoss-workflow:
    uses: ./.github/workflows/scanoss.yml
    with:
       FILTERED_PATH: 'comp1'