name: Scanoss - SRC

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'


jobs:
  call-scanoss-workflow:
    uses: ./.github/workflows/scanoss.yml
    with:
       FILTERED_PATH: 'src'