name: Scanoss - comp1

on:
  pull_request:
    paths:
      - 'comp1/**'

permissions:
  contents: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  call-scanoss-workflow:
    uses: ./.github/workflows/scanoss.yml
    with:
       FILTERED_PATH: 'comp1'
    secrets: inherit