name: Scanoss - scanner.c

on:
  pull_request:
    paths:
      - 'scanner.c/**'

permissions:
  contents: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  call-scanoss-workflow:
    uses: ./.github/workflows/scanoss.yml
    with:
      FILTERED_PATH: 'scanner.c'
    secrets: inherit